//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazCarProjectServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelUnit
    {
        public int ModelID { get; set; }
        public string Manufactor { get; set; }
        public string ModelName { get; set; }
        public int Mileage { get; set; }
        public string IsAvileable { get; set; }
        public string OnRipair { get; set; }
        public int PlateNumber { get; set; }
        public string Photo { get; set; }
        public string Branch { get; set; }
    }
}
